# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Global Settings
timezone: "Asia/Kolkata"

# Site settings
title: Akshar's Blog
author: Akshar Patel
email: akshar.patel.47@gmail.com
description: > # 
    Logs of my Experiments, Opinions and Learnings while creating Apps for the Real World.  
baseurl: ""
url: "https://aksharpatel47.github.io" # the base hostname & protocol for your site
twitter_username: aksharpatel47
github_username:  aksharpatel47

# Build settings
markdown: kramdown
